server:
  port: 8080

management:
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
#curl -X POST http://localhost:8080/actuator/shutdown

spring:
  data:
    rest:
      basePath: /api
  datasource:
    password: ''
    platform: hsqldb
#    url: jdbc:hsqldb:file:db/hsqlDb
    username: SA
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7777/eureka/